### ISSUE TITLE
Symlink Path Issues for assets: Absolute Path in Local Environment Breaks in Production on Linux

### ISSUE THREAD

**Issue by yann120** [Shopify/shopify-app-template-ruby#108]
# Issue summary

When deploying to a production environment (on fly.io with Linux), the application encounters a `Errno::ENOENT` error related to a symlink pointing to `index.html` in the `public/dist` directory. This symlink is generated correctly in a local Mac environment but fails in production due to its absolute path.

- shopify_api version: 21.4
- shopify_app version: 21.4
- Ruby version: 3.1
- Operating system: Mac for development, Linux on fly.io for production

```
Errno::ENOENT
No such file or directory @ rb_sysopen - /app/public/dist/index.html
```

On a local Mac development machine:
```
➜  dist git:(main) ✗ ls -l
total 0
lrwxr-xr-x  1 yann  staff  98 Oct 12 15:03 index.html -> /Users/yann/Code/shopify/shopify_app/web/lib/tasks/../../frontend/dist/index.html
```

## Expected behavior

The symlink for `index.html` should be relative and should resolve correctly regardless of the deployment environment, ensuring that the application can locate the `index.html` file.

## Actual behavior

The symlink generated has an absolute path which works on the local Mac development environment but breaks when deployed to a production environment on fly.io with Linux.

## Steps to reproduce the problem

1. Run the Rake task that generates the symlink in a local Mac environment : `rake build:all`
2. Verify that the symlink is absolute and points to the correct `index.html` on the local machine.
3. Deploy the application to a production environment on fly.io with Linux.
4. Observe the `Errno::ENOENT` error when the application tries to access the `index.html` via the symlink.

**Comment by guilhermeprokisch** [comment]
I'm also having this problem. I tried to use your PR branch but I'm still getting it, have you managed to solve it?

 => ERROR [ 8/10] RUN rake build:all                                                 5.9s
------
 > [ 8/10] RUN rake build:all:
#0 5.801 rake aborted!
#0 5.801 Errno::ENOENT: No such file or directory @ rb_file_s_symlink - (../../frontend/dist/index.html, /app/lib/tasks/../../public/dist/index.html)         
#0 5.801 /app/lib/tasks/build.rake:23:in `symlink'
#0 5.801 /app/lib/tasks/build.rake:23:in `make_symlink'
#0 5.801 /app/lib/tasks/build.rake:23:in `block (2 levels) in <main>'
#0 5.801 /usr/local/bundle/gems/sentry-ruby-5.12.0/lib/sentry/rake.rb:24:in `execute'
#0 5.801 Tasks: TOP => build:all => build:build_frontend_links
#0 5.801 (See full trace by running task with --trace)
------
Error: failed to fetch an image or build from source: error building: failed to solve: executor failed running [/bin/sh -c rake build:all]: exit code: 1

**Comment by whiskerside** [comment]
Actually, the `npm run build` command should be ran on the server side, not development environment.
