### ISSUE TITLE
Update to App Bridge 4.x ?

### ISSUE THREAD

**Issue by key88sf** [Shopify/shopify-app-template-ruby#139]
Hi - can this repo be updated to work with the latest App Bridge v4? I have a live app build with this Ruby template using AppBridge v3, and looking at the Shopify migration guide (https://shopify.dev/docs/api/app-bridge/migration-guide), it's unclear where exactly some of the changes need to be made in this template app. It would be great if this repo was updated and folks like me could compare to existing apps. WDYT?

**Comment by lizkenyon** [comment]
Hey there 👋 

We actually just merged these changes, but haven't pulled in these changes to the template just yet.

You can review the changes that were required in this [PR](https://github.com/Shopify/shopify-frontend-template-react/pull/255).

**Comment by key88sf** [comment]
@lizkenyon Aha, great. Thank you! 👍

**Comment by douglasmiller** [comment]
I might be missing something obvious, but the env var replacement does not occur when I pull in the changes from the linked pull request.

Will there be more changes necessary in the rails template to accommodate the react template's updates?

**Comment by key88sf** [comment]
@lizkenyon Ok thanks. For future huge changes like this, it would be great to have a migration guide specifically for folks using apps based on this template as well. I'm doing the changes now and there is a lot of stuff to work out...
