### ISSUE TITLE
All app links open in new tab?!

### ISSUE THREAD

**Issue by key88sf** [Shopify/shopify-app-template-ruby#149]
I created a new Shopify app using the template. Whenever I add any Polaris element that uses an anchor element, the links open new tabs instead of the current window. For exampe, adding the following to the default `index.jsx` page:

```
<Link url="/pagename">Click me</Link>
```

results in a link where clicking it opens a *new tab* instead of it operating on the current window location.  This never happened before with AppBridge 3.x.  Also the URL it is opening seems to be relative to the backend rails host name.  For example, if the current window location is `https://admin.shopify.com/store/my-dev-store/apps/test-app`,  the URL of the new tab is: `https://<cloudflare-rails-host-name>/pagename`  --- so not even relative to the current window location.

Any ideas why this is happening now?

**Comment by lizkenyon** [comment]
I am going to close this ticket. We will provide updates on this [ticket.](https://github.com/Shopify/shopify-frontend-template-react/issues/306)
