### ISSUE TITLE
Can't run the app after unplugging the React frontend

### ISSUE THREAD

**Issue by remy727** [Shopify/shopify-app-template-ruby#150]
I unplugging the React frontend by following the steps in Wiki page.

But I can't preview the app. I ran the app using Ngrok tunnel but I always have ERR_NGROK_8012 error. I tried different ports and checked firewall but the same error. I tried original ruby template but it worked well.
You can reproduce the issue on [shopify-app-template-ruby-demo](https://github.com/remy727/shopify-app-template-ruby-demo)

![Image](https://github.com/user-attachments/assets/52665d27-9abb-4725-aec0-c9eb694bfc1f)

**Comment by remy727** [comment]
It works. Thank you, @cesarho 👍

**Comment by matteodepalo** [comment]
Thank you @remy727, I've updated the wiki.
