### ISSUE TITLE
Default template breaks. Missing  keyword: :session_storage

### ISSUE THREAD

**Issue by artyrcheek** [Shopify/shopify-app-template-ruby#57]
# Issue summary

Template breaks on initialization, I seem to get this error
```
/.../shopify_api-12.2.1/lib/shopify_api/context.rb:44:in `setup': missing  keyword: :session_storage (ArgumentError)
```
It seems if I revert the changes in [this commit](https://github.com/Shopify/shopify-app-template-ruby/commit/00642e933774c97de2ed8783de6a45977e1e6a90). I can get everything working again

Maybe I'm being silly and its an issue with versions?

**Comment by artyrcheek** [comment]
@klenotiw I imagine you know why this is happening. Is it an issue with my versions?
```
DIRECTORY COMPONENTS               

web
📂 web
  📂 backend    web
  📂 frontend   web/frontend

ACCESS SCOPES IN ROOT TOML FILE    
write_products

TOOLING AND SYSTEM                 
Shopify CLI       3.25.0
Package manager   npm
OS                darwin-arm64
Shell             /bin/zsh
Node version      v16.13.2
```

**Comment by klenotiw** [comment]
Sorry about that, we just [reverted that commit](https://github.com/Shopify/shopify-app-template-ruby/pull/58). It was just a dumb mistake by us. Thanks so much for reaching out!
