### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by ElliottRoche** [Shopify/shopify-app-template-ruby#65]
## Overview/summary
Does this template support typescript? I've noticed the generated JS is just JS and I didn't notice any options during set up to use typescript.
...

## Motivation

> What inspired this enhancement?

Typescript is widely used, particularly for projects that use React, vite, GraphQL, etc.

### Area

- [ ✅] Add any relevant `Area: <area>` labels to this issue

## Checklist

- [✅ ] I have described this enhancement in a way that is actionable (if possible)

**Comment by jefflewis** [comment]
TS has not been added. This issue is valid and not stale, bot.

**Comment by BaggioGiacomo** [comment]
I think it's better if you open the same issue [here](https://github.com/Shopify/shopify-frontend-template-react)

**Comment by jefflewis** [comment]
Being a ruby template for the app, they really should have the front-end piece of this far more configurable. As-is, the options are very much hard coded into the configurattion. It's very very much against the "convention over configuration" ethos for rails. I've spent _hours_ fiddling with the JS configuration of the server to get it to work properly.

So if they want a JS only version, maybe have that be an option. TS support could be a flag that generates a TS version of the app when passed a flag. This is how most other JS template apps work from react, vue, react-native, etc.
